name: Build Android APK

on:
  push:
    branches:
      - main  # Change this if using a different branch

jobs:
  build:
    name: Build Release APK
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java and Gradle
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 18  # Use the version your project requires

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.1.0

      - name: Install Dependencies
        run: yarn install  # Use `npm install` if you prefer npm

      - name: Auto-Increment App Version
        run: |
          VERSION_CODE=$(grep "versionCode" android/app/build.gradle | awk '{print $2}')
          NEW_VERSION_CODE=$((VERSION_CODE + 1))
          VERSION_NAME=$(grep "versionName" android/app/build.gradle | awk -F '"' '{print $2}')
          NEW_VERSION_NAME=$(echo $VERSION_NAME | awk -F. -v OFS=. '{$NF+=1; print}')
          
          # Update build.gradle
          sed -i "s/versionCode $VERSION_CODE/versionCode $NEW_VERSION_CODE/" android/app/build.gradle
          sed -i "s/versionName \"$VERSION_NAME\"/versionName \"$NEW_VERSION_NAME\"/" android/app/build.gradle
          
          echo "Updated versionCode to $NEW_VERSION_CODE"
          echo "Updated versionName to $NEW_VERSION_NAME"

      - name: Commit Version Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add android/app/build.gradle
          git commit -m "CI: Bump version to $NEW_VERSION_NAME ($NEW_VERSION_CODE)"
          git push

      - name: Run Tests
        run: |
          yarn test --ci --passWithNoTests

      - name: Decode Keystore File
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
        run: |
          echo "$ANDROID_KEYSTORE_BASE64" | base64 --decode > android/app/my-release-key.jks

      - name: Build Release APK
        env:
          MYAPP_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          MYAPP_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          MYAPP_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        run: |
          cd android
          ./gradlew assembleRelease --no-daemon

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-arm64-v8a-release-apk
          path: android/app/build/outputs/apk/release/app-arm64-v8a-release.apk #As per architecture
        # with:
        #   name: app-release-apk
        #   path: android/app/build/outputs/apk/release/app-release.apk
