name: iOS CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest # Uses macOS runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.1.0

      - name: Install dependencies
        run: |
          npm install
          cd ios && pod install && cd ..

      - name: Set up Ruby and Bundler
        run: |
          sudo gem install bundler
          cd ios && bundle install && cd ..

      - name: Build iOS app
        run: |
          cd ios
          xcodebuild clean archive \
            -workspace DebugExam.xcworkspace \
            -scheme DebugExam \
            -archivePath $PWD/build/DebugExam.xcarchive \
            -destination 'generic/platform=iOS' \
            CODE_SIGN_IDENTITY="iPhone Developer" \
            DEVELOPMENT_TEAM="${{ secrets.IOS_DEVELOPMENT_TEAM }}" \
            PROVISIONING_PROFILE_SPECIFIER="${{ secrets.IOS_PROVISIONING_PROFILE }}"

      - name: Export IPA
        run: |
          cd ios
          xcodebuild -exportArchive \
            -archivePath $PWD/build/DebugExam.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath $PWD/build/output

      - name: Upload IPA as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: iOS-App
          path: ios/build/output/*.ipa

  deploy:
    needs: build
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download IPA from Artifact
        uses: actions/download-artifact@v4
        with:
          name: iOS-App
          path: ios/build/output

      # - name: Deploy to TestFlight
      #   env:
      #     APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
      #     APP_STORE_CONNECT_API_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_ISSUER_ID }}
      #     APP_STORE_CONNECT_API_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_API_KEY_CONTENT }}
      #   run: |
      #     cd ios
      #     fastlane run upload_to_testflight
