name: iOS CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.1.0

      - name: Install dependencies
        run: |
          yarn install
          cd ios
          gem install cocoapods
          pod install
          cd ..

      - name: Set up signing environment
        run: |
          echo ${{ secrets.APPLE_CERTIFICATE }} | base64 --decode > /tmp/certificate.p12
          security create-keychain -p "" build.keychain
          security import /tmp/certificate.p12 -t agg -k ~/Library/Keychains/build.keychain -P ${{ secrets.CERTIFICATE_PASSWORD }} -A
          security list-keychains -s ~/Library/Keychains/build.keychain
          security default-keychain -s ~/Library/Keychains/build.keychain
          security unlock-keychain -p "" ~/Library/Keychains/build.keychain
          security set-key-partition-list -S apple-tool:,apple: -s -k "" ~/Library/Keychains/build.keychain
        env:
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}

      - name: Build iOS app
        run: |
          cd ios
          xcodebuild clean archive \
            -workspace DebugExam.xcworkspace \
            -scheme DebugExam \
            -archivePath $PWD/build/DebugExam.xcarchive \
            -destination 'generic/platform=iOS' \
            CODE_SIGN_IDENTITY="iPhone Developer" \
            DEVELOPMENT_TEAM="${{ secrets.IOS_DEVELOPMENT_TEAM }}" \
            PROVISIONING_PROFILE_SPECIFIER="${{ secrets.PROVISIONING_PROFILE }}" \
            CODE_SIGN_STYLE=Automatic \
            -allowProvisioningUpdates

      - name: Export IPA
        run: |
          cd ios
          xcodebuild -exportArchive \
            -archivePath $PWD/build/DebugExam.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath $PWD/build/output \
            -allowProvisioningUpdates

      - name: Upload IPA as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: iOS-App
          path: ios/build/output/*.ipa