name: Build iOS Release

on:
  push:
    branches:
      - main  # Change this if your branch is different

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Xcode
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      - name: Install Dependencies
        run: |
          cd ios
          pod install --repo-update

      - name: Decode Certificates and Profiles
        env:
          P12_BASE64: ${{ secrets.IOS_CERTIFICATE }}
          MOBILEPROVISION_BASE64: ${{ secrets.IOS_PROVISION }}
        run: |
          echo "$P12_BASE64" | base64 --decode > ios_certificate.p12
          echo "$MOBILEPROVISION_BASE64" | base64 --decode > ios_profile.mobileprovision

      - name: Import Certificate
        run: |
          security create-keychain -p "tempPassword" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "tempPassword" build.keychain
          security import ios_certificate.p12 -k build.keychain -P "${{ secrets.IOS_CERTIFICATE_PASSWORD }}" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "tempPassword" build.keychain

      - name: Move Provisioning Profile
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          mv ios_profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

      - name: Build IPA
        run: |
          cd ios
          xcodebuild -workspace YourApp.xcworkspace \
          -scheme YourApp \
          -sdk iphoneos \
          -configuration Release \
          -archivePath $PWD/build/YourApp.xcarchive archive

      - name: Export IPA
        run: |
          cd ios
          xcodebuild -exportArchive \
          -archivePath $PWD/build/YourApp.xcarchive \
          -exportOptionsPlist exportOptions.plist \
          -exportPath $PWD/build/

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-app
          path: ios/build/*.ipa
